baseURL = 'https://opensyndrome.org/'
languageCode = 'en-us'
title = 'Open Syndrome Initiative'
copyright = 'Ana Paula Gomes Ferreira'

[pagination]
  pagerSize = 15

[outputs]
  home = ["HTML", "RSS", "JSON"]
