[[main]]
  name = "About"
  pageRef = "about"
  weight = 3

[[main]]
  name = "Definitions"
  pageRef = "definitions"
  weight = 1

[[main]]
  name = "How"
  pageRef = "how"
  weight = 2

[[main]]
  name = "GitHub"
  url = "https://github.com/OpenSyndrome/website/"
  weight = 30
  [main.params]
    icon = "github"
    showName = false
    target = "_blank"

[[main]]
  identifier = "appearance"
  weight = 40
  [main.params]
    action = "appearance"
    icon = "sun"

[[main]]
  identifier = "search"
  weight = 99
  [main.params]
    action = "search"
    icon = "search"

[[footer]]
  name = "Tags"
  pageRef = "tags"

[[footer]]
  name = "How to cite"
  pageRef = "blog/how-to-cite"

[[footer]]
  name = "Blog"
  pageRef = "blog"

[[footer]]
  name = "GitHub"
  url = "https://github.com/OpenSyndrome/"
